query projectTimes($clientId: Int!) {
  project(
    where: {
      _and: { client_id: { _eq: $clientId }, project_times: { invoice_id: { _is_null: true } } }
    }
  ) {
    client {
      name
    }
    name
    project_times {
      id
      end_time
      invoice_id
      start_time
      description
    }
  }
}
