query tasks($limit: Int, $offset: Int, $order_by: [task_order_by!], $where: task_bool_exp) {
  task(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    id
    title
    priority
    description
    due_date
    project {
      name
    }
    task_viewed_bies {
      dragon_user {
        id
      }
    }
  }
  task_aggregate(order_by: $order_by, where: $where) {
    aggregate {
      count
    }
  }
}
