mutation stopAllTimers($userId: String!, $endTime: timestamp!) {
  update_project_time(
    _set: { end_time: $endTime }
    where: { dragon_user_id: { _eq: $userId }, end_time: { _is_null: true } }
  ) {
    returning {
      id
    }
  }
}
