mutation updateTransfers(
  $sourceGic: Int!
  $matchedGic: Int!
  $transactionType: String!
  $notes: String
  $sourceTransfer: Int!
  $matchedTransfer: Int!
) {
  updateSource: update_accounting_transactions_by_pk(
    _set: {
      gic_id: $sourceGic
      notes: $notes
      transaction_type: $transactionType
      related_transaction: $matchedTransfer
    }
    pk_columns: { id: $sourceTransfer }
  ) {
    id
  }
  updateMatch: update_accounting_transactions_by_pk(
    _set: {
      gic_id: $matchedGic
      notes: $notes
      transaction_type: $transactionType
      related_transaction: $sourceTransfer
    }
    pk_columns: { id: $matchedTransfer }
  ) {
    id
  }
}
