mutation updateTransfers(
  $sourceGic: Int!
  $matchedGic: Int!
  $notes: String
  $sourceTransfer: String!
  $matchedTransfer: String!
) {
  updateSource: update_accounting_transactions_by_pk(
    _set: {
      gic_category_id: $sourceGic
      notes: $notes
      related_transaction_id: $matchedTransfer
    }
    pk_columns: { id: $sourceTransfer }
  ) {
    id
  }
  updateMatch: update_accounting_transactions_by_pk(
    _set: {
      gic_category_id: $matchedGic
      notes: $notes
      related_transaction_id: $sourceTransfer
    }
    pk_columns: { id: $matchedTransfer }
  ) {
    id
  }
}
