query credits(
  $limit: Int
  $offset: Int
  $order_by: [accounting_credit_order_by!]
  $where: accounting_credit_bool_exp
) {
  accounting_credit(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    id
    account {
      name
    }
    amount
    date
    description
    gic {
      name
    }
    notes
  }
  accounting_credit_aggregate(order_by: $order_by, where: $where) {
    aggregate {
      count
    }
  }
}
