mutation setTransactionPurpose($id: Int!, $purpose: transaction_purpose_enum!) {
  update_transaction(where: { id: { _eq: $id } }, _set: { transaction_purpose: $purpose }) {
    returning {
      id
    }
  }
}
