query transactions($limit: Int, $offset: Int, $order_by: [accounting_transactions_order_by!], $where: accounting_transactions_bool_exp) {
  accounting_transactions(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    id
    account_id
    account {
      name
    }
    debit
    credit
    name
    currency
    merchant_name
    date
    gic_category_id
    gicCategory {
      name
      is_business
    }
    personal_finance_category
    personal_finance_category_confidence
    personalCategory {
      hierarchy
    }
    relatedTransaction {
      id
      name
      merchant_name
      debit
      credit
      gic_category_id
      gicCategory {
        is_business
        name
      }
    }
    recommendations {
      recommendation {
        id
      }
    }
    notes
    appliedRule {
      id
      name
    }
  }
  accounting_transactions_aggregate(order_by: $order_by, where: $where) {
    aggregate {
      count
    }
  }
}
