mutation addProjectTimes($invoiceId: Int!, $projectTimeIds: [Int!]) {
  update_project_time_many(
    updates: {
      where: { _and: { invoice_id: { _is_null: true }, id: { _in: $projectTimeIds } } }
      _set: { invoice_id: $invoiceId }
    }
  ) {
    returning {
      id
    }
  }
}
