mutation createInvoice($client_id: Int!, $due_date: timestamp, $contractorId: Int) {
  insert_invoice_one(
    object: { client_id: $client_id, contractor_id: $contractorId, due_date: $due_date }
  ) {
    id
  }
}
