mutation createInvoiceItem(
  $description: String!
  $price: float8!
  $tax: float8!
  $currency: String!
  $invoiceId: Int!
) {
  insert_invoice_item(
    objects: {
      description: $description
      price: $price
      tax: $tax
      currency: $currency
      invoice_id: $invoiceId
    }
  ) {
    returning {
      id
    }
  }
}
