mutation MyMutation($invoiceId: Int!, $projectTimeId: Int!) {
  update_project_time_many(
    updates: {
      where: { _and: { invoice_id: { _is_null: true }, id: { _eq: $projectTimeId } } }
      _set: { invoice_id: $invoiceId }
    }
  ) {
    returning {
      id
    }
  }
}
