mutation updateProjectTimes($invoiceId: Int!, $projectId: Int!) {
  update_project_time_many(
    updates: {
      _set: { invoice_id: $invoiceId }
      where: { _and: { invoice_id: { _is_null: true }, project_id: { _eq: $projectId } } }
    }
  ) {
    returning {
      id
    }
  }
}
