mutation updateProjectTimes($invoiceId: Int!) {
  update_project_time_many(
    updates: { _set: { invoice_id: $invoiceId }, where: { invoice_id: { _is_null: true } } }
  ) {
    returning {
      id
    }
  }
}
