mutation updateTransaction(
  $category: Int!
  $transactionType: String!
  $notes: String
  $transactionIds: [String!]
) {
  update_accounting_transactions_many(
    updates: {
      _set: { gic_category_id: $category, notes: $notes, transaction_type: $transactionType }
      where: { id: { _in: $transactionIds } }
    }
  ) {
    affected_rows
  }
}
