mutation updateTransactions(
  $transactionIds: jsonb!,
  $category: Int!,
  $transactionType: String!,
  $notes: String,
  $tax: Int
) {
  accounting_update_transactions(
    args: {
      composite_keys: $transactionIds,
      new_category: $category,
      new_transaction_type: $transactionType,
      new_notes: $notes,
      new_tax: $tax
    }
  ) {
    id
  }
}
