mutation createContractor(
  $name: String!
  $contract_id: Int!
  $gpt_persona: String
  $location: String!
  $rate: float8!
  $markup: float8!
  $start_date: timestamp!
  $end_date: timestamp
) {
  insert_contractor_one(
    object: {
      name: $name
      contract_id: $contract_id
      gpt_persona: $gpt_persona
      location: $location
      start_date: $start_date
      end_date: $end_date
      markup: $markup
      contractor_rate: { data: { rate: $rate } }
    }
  ) {
    id
  }
}
