mutation updatePaymentInfo(
  $id: Int!
  $method: String!
  $swift: String
  $swift_iban: String
  $ach_routing: String
  $ach_account: String
  $usdt_wallet: String
) {
  update_accounting_payment_info(
    where: { id: { _eq: $id } }
    _set: {
      method: $method
      swift: $swift
      swift_iban: $swift_iban
      ach_routing: $ach_routing
      ach_account: $ach_account
      usdt_wallet: $usdt_wallet
    }
  ) {
    returning {
      id
      method
    }
  }
}
