mutation updateContractor(
  $id: Int!
  $image_id: Int
  $contract_id: Int
  $first_name: String!
  $last_name: String!
  $country: String!
  $city: String!
  $address: String!
  $post_code: String!
  $personal_email: String!
  $work_email: String!
  $rate_id: Int
  $rate: float8
  $markup: float8
  $gpt_persona: String
  $start_date: timestamp
  $end_date: timestamp
) {
  update_contractor(
    _set: {
      image_id: $image_id
      first_name: $first_name
      last_name: $last_name
      country: $country
      city: $city
      address: $address
      post_code: $post_code
      personal_email: $personal_email
      work_email: $work_email
      contract_id: $contract_id
      rate_id: $rate_id
      markup: $markup
      gpt_persona: $gpt_persona
      start_date: $start_date
      end_date: $end_date
    }
    where: { id: { _eq: $id } }
  ) {
    returning {
      id
    }
  }
  update_contractor_rate(where: { id: { _eq: $rate_id } }, _set: { rate: $rate }) {
    returning {
      id
    }
  }
}
