mutation updateContractor(
  $id: Int!
  $contract_id: Int
  $name: String
  $location: String
  $rate_id: Int
  $rate: float8
  $markup: float8
  $gpt_persona: String
  $start_date: timestamp
  $end_date: timestamp
) {
  update_contractor(
    _set: {
      name: $name
      contract_id: $contract_id
      location: $location
      rate_id: $rate_id
      markup: $markup
      invoice: $invoice
      gpt_persona: $gpt_persona
      start_date: $start_date
      end_date: $end_date
    }
    where: { id: { _eq: $id } }
  ) {
    returning {
      id
    }
  }
  update_contractor_rate(where: { id: { _eq: $rate_id } }, _set: { rate: $rate }) {
    returning {
      id
    }
  }
}
