mutation createClient($name: String!, $description: String!, $gpt_persona: String!, $start_date: timestamp) {
  insert_client_one(object: { name: $name, description: $description, gpt_persona: $gpt_persona, start_date: $start_date }) {
    id
  }
}
