query invoice($id: Int!) {
  invoice_by_pk(id: $id) {
    due_date
    id
    client_id
    project_times(where: { deleted_at: { _is_null: true } }) {
      id
      invoice_id
    }
    invoice_items(where: { deleted_at: { _is_null: true } }) {
      id
      key: id
      description
      currency
      tax
      price
    }
  }
}
