mutation createRule(
  $name: String!
  $account_id: String
  $tax_id: Int
  $gic_id: Int!
  $transaction_regex: String!
  $rule_type: rule_type!
) {
  insert_accounting_rules_one(
    object: {
      name: $name
      account_id: $account_id
      tax_id: $tax_id
      gic_id: $gic_id
      transaction_regex: $transaction_regex
      rule_type: $rule_type
    }
  ) {
    id
  }
}
