query rule($id: Int!) {
  accounting_rules_by_pk(id: $id) {
    id
    name
    account_id
    tax_id
    rule_type
    transaction_regex
    gic_id
    category {
      id
      name
      is_business
    }
  }
}
