mutation createTask(
  $userId: String!
  $title: String!
  $project_id: Int!
  $priority: Int!
  $status: String!
  $description: String
  $due_date: timestamp
) {
  insert_task_one(
    object: {
      user_id: $userId
      title: $title
      project_id: $project_id
      priority: $priority
      status: $status
      description: $description
      due_date: $due_date
    }
  ) {
    id
  }
}
