query contractor($id: Int!) {
  contractor(where: { id: { _eq: $id } }) {
    id
    name
    location
    contractor_rate {
      rate
    }
    invoice
    gpt_persona
    start_date
    end_date
    document
  }
}
