query secrets($where: secret_bool_exp!, $limit: Int, $offset: Int, $order_by: [secret_order_by!]) {
  secret(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    path
    projects {
      name
    }
  }
  secret_aggregate(order_by: $order_by, where: $where) {
    aggregate {
      count
    }
  }
}
