query userProjects($userId: String!) {
  dragon_user(where: {id: {_eq: $userId}}) {
    name
    contractor {
      id
      name
      projects {
        project {
          id
          name
          project_times {
            id
            start_time
            end_time
          }
          client {
            name
          }
        }
      }
    }
  }
}
