query contractors(
  $limit: Int
  $offset: Int
  $order_by: [contractor_order_by!]
  $where: contractor_bool_exp
) {
  contractor(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    id
    name
    location
    gpt_persona
    document
    rate
    invoice
    start_date
    end_date
    created_at
    deleted_at
    archived_at
  }
  contractor_aggregate(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    aggregate {
      count
    }
  }
}
