query debits($isBusiness: Boolean!) {
  accounting_transactions(
    where: {
      debit: { _is_null: false }
      gic_category_id: { _is_null: false }
      account: { excluded: { _eq: false } }
      gicCategory: { is_business: { _eq: $isBusiness } }
    }
  ) {
    debit
    tax_charged
    account {
      currency
    }
  }
}
